### ISSUE TITLE
Installing xmake via the deb package doesn't install xrepo

### ISSUE THREAD

**Issue by MoAlyousef** [xmake-io/xrepo#2]
I just thought I would report this since it doesn't seem to be the intended behavrior.
It's not a big problem.  ```xmake l private.xrepo <args>``` works and I was still able to install the shell script manually.

**Comment by waruqi** [comment]
Oh, I forgot to add it to the deb package, I will add it later. Thank you.

**Comment by waruqi** [comment]
I have added it to deb package. You can download deb and test it from ci/artifacts. https://github.com/xmake-io/xmake/actions/runs/385359964

**Comment by MoAlyousef** [comment]
Thank you
