### ISSUE TITLE
mac 使用C++包fmt失败

### ISSUE THREAD

**Issue by ethanvc** [xmake-io/xrepo#22]
### 描述问题

C++项目依赖fmt后，安装fmt失败。

### 期待的结果

安装成功。

### 错误信息

ote: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> protobuf-cpp 3.17.3 
  -> fmt 8.0.1 
please input: y (y/n/m)

  => install fmt 8.0.1 .. failed

clang: error: invalid version number in '-mmacosx-version-min=11.4'
if you want to get more verbose errors, please see:

### 相关环境

请提供编译和运行环境信息，下面是一些必须填写的基础信息，便于我们针对性排查问题：

- xmake版本：v2.5.9
- xmake运行平台：mac
- xmake目标平台：mac

**Comment by waruqi** [comment]
我这周没空看，你可以先自己调下仓库包，或者加 -vD 看下详情

等下周二之后我才有空给你看下

**Comment by ethanvc** [comment]
> 我这周没空看，你可以先自己调下仓库包，或者加 -vD 看下详情
> 
> 等下周二之后我才有空给你看下

已经解决了，貌似是苹果系统的问题。我这边的解决方法是：
1. 升级 MAC系统到最新版。
2. 执行命令：sudo xcode-select -s /Library/Developer/CommandLineTools（参考：https://stackoverflow.com/questions/9477860/xcode-select-switch-path-when-using-cli-toolkit）

多谢关注。
