### ISSUE TITLE
Cannot `xrepo remove package`. package(pkg) not found.

### ISSUE THREAD

**Issue by Ramblestsad** [xmake-io/xrepo#24]
### Xmake Version

2.7.1+HEAD.0162040

### Operating System Version and Architecture

macOS Monterey 12.5.1

### Describe Bug

<img width="604" alt="image" src="https://user-images.githubusercontent.com/45003009/188531815-7810d986-cfbf-43b0-9329-d0d328bab260.png">
<img width="766" alt="image" src="https://user-images.githubusercontent.com/45003009/188531885-0bc95e5c-3606-49d6-bc83-a83e4b465431.png">

### Expected Behavior

Successfully removed the selected package.

**Comment by Ramblestsad** [comment]
BTW, when I `xrepo install fmt`, there is something wrong too.
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/45003009/188532105-f4fd3a7f-f992-40c5-9f2c-b9c275b42dc1.png">

**Comment by Ramblestsad** [comment]
> BTW, when I `xrepo install fmt`, there is something wrong too. <img alt="image" width="1203" src="https://user-images.githubusercontent.com/45003009/188532105-f4fd3a7f-f992-40c5-9f2c-b9c275b42dc1.png">

**Comment by waruqi** [comment]
try `xrepo remove --all fmt`

**Comment by waruqi** [comment]
> BTW, when I `xrepo install fmt`, there is something wrong too. <img alt="image" width="1203" src="https://user-images.githubusercontent.com/45003009/188532105-f4fd3a7f-f992-40c5-9f2c-b9c275b42dc1.png">

just network issue

**Comment by Ramblestsad** [comment]
> try `xrepo remove --all fmt`

Solved. Thanks for the time.

**Comment by Ramblestsad** [comment]
> > BTW, when I `xrepo install fmt`, there is something wrong too. <img alt="image" width="1203" src="https://user-images.githubusercontent.com/45003009/188532105-f4fd3a7f-f992-40c5-9f2c-b9c275b42dc1.png">
> 
> just network issue

Closed.
