### ISSUE TITLE
error: fatal: couldn't find remote ref main

### ISSUE THREAD

**Issue by Lzeyuan** [xmake-io/xrepo#29]
### Xmake 版本

v2.7.3+master.b312e3b6a

### 操作系统版本和架构

windows 10 21H2

### 描述问题

![image](https://user-images.githubusercontent.com/51223122/208000962-c0033688-ce8e-4e73-b883-e40e67f9434c.png)
全新下载的压缩包xmake，使用xrepo搜索gest找不到分支，试了xrepo env可以使用。
另一台同样系统版本的电脑可以找到gtest无报错。

### 期待的结果

找到gtest包

### 工程配置

无

### 附加信息和错误日志

无

**Comment by waruqi** [comment]
%localappdata%/.xmake/repositories 目录删了再试试

**Comment by Lzeyuan** [comment]
解决了，感谢大佬。
