### ISSUE TITLE
Freetype not installing

### ISSUE THREAD

**Issue by SeanRamey** [xmake-io/xrepo#3]
Xrepo will not install freetype. On discord, we determined that it was because xrepo can't find the `BrotliDecoderDecompress` symbol on my system's brotli library. The issue is that my system's brotli install seperates the library into 3 files: `libbrotlicommon-static.a`, `libbrotlienc-static.a`, and `libbrotlidec-static.a`. The file `libbrotlidec-static.a` is where the `BrotliDecoderDecompress` symbol is defined.

### Expected behavior
Should install without issue.

### Error output
`[sean@sean-pc-arch ~]$ xrepo install freetype
note: try installing these packages (pass -y to skip confirm)?
in xmake-repo:
  -> freetype 2.10.4 
please input: y (y/n)
y
  => install freetype 2.10.4 .. failed
if you want to get verbose errors, please see:
  -> /home/sean/.xmake/cache/packages/2103/f/freetype/2.10.4/installdir.failed/logs/install.txt
error: install failed!
error: execv(xmake require -j 9 --extra={system=false} freetype) failed(255)`

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

### Related Environment
- xmake version: 2.5.2
- os: arch-linux
- target platform: x86-64

**Comment by waruqi** [comment]
you can run `xmake f -c -vD` and let me see the verbose errors

**Comment by waruqi** [comment]
This is because xmake/xrepo will first find the system brotli library, I will improve find_package("brotli") to support it.

**Comment by SeanRamey** [comment]
> This is because xmake/xrepo will first find the system brotli library, I will improve find_package("brotli") to support it.

This particular issue is not really because it finds the system library. There is an issue finding a symbol because it's not looking for the right file in the system library.

**Comment by waruqi** [comment]
I have improved it, see https://github.com/xmake-io/xrepo/issues/4#issuecomment-794788058
