### ISSUE TITLE
添加清理时只清理缓存的功能

### ISSUE THREAD

**Issue by 233lol** [xmake-io/xrepo#30]
### 你在什么场景下需要该功能？

xrepo clean 清理是没有使用的包和缓存一起清理，还要自己选择是否清理某些包。
有时候只需清理包的构建缓存和下载缓存，不需要清理包。

### 描述可能的解决方案

添加只清理缓存的选项

**Comment by waruqi** [comment]
回头我看下，另外 dev 分支对包缓存也做了优化，会比上个版本省更多空间

**Comment by waruqi** [comment]
加上了 `xrepo clean --cache`

dev 版本 `xmake update -s dev`
