### ISSUE TITLE
Using Xmake-repo by default

### ISSUE THREAD

**Issue by unknown989** [xmake-io/xrepo#33]
### Is your feature request related to a problem? Please describe.

When I first started using xrepo I couldn't figure out why I can't install packages, but later on I figured it's because there's no repository attached even though `xmake list-repo` shows me that xmake-repo is used.
but it was fixed when I added it `xrepo add-repo xmake-repo https://github.com/xmake-io/xmake-repo`

### Describe the solution you'd like

I think xrepo by default should fall back the **xmake-repo** whenever an error is found.

**Comment by waruqi** [comment]
https://github.com/xmake-io/xmake-repo is the built-in repository and it will always be used. You don't need to add it manually.

If you encounter errors, you should provide error logs with -vD to solve the problem.
