### ISSUE TITLE
Fail to install assimp 5.2.4 at (vs_runtime="MTd" and debug=true)

### ISSUE THREAD

**Issue by Kethers** [xmake-io/xrepo#37]
### Xmake 版本

v2.8.5+dev.1ccbc20e7

### 操作系统版本和架构

Windows11 22H2 22621.2861

### 描述问题

Using VS2022 as toolchain and below statement in xmake
`add_requires("assimp >= 5.2.4", {configs = {debug = true, vs_runtime = "MTd"}} )`

Fail to install it, the detailed output log shows there's something wrong with the "/EHsc" flags and all these warnings are considered as errors.

### 期待的结果

Should install successfully.

### 工程配置

`add_requires("assimp >= 5.2.4", {configs = {debug = true, vs_runtime = "MTd"}} )`

### 附加信息和错误日志

[install.txt](https://github.com/xmake-io/xrepo/files/13766660/install.txt)

**Comment by waruqi** [comment]
这个的版本限制得调整下，可以提个 pr 过来 https://github.com/xmake-io/xmake-repo/blob/fb077c505b04a8e2c534da6828ab31e13d4ebf54/packages/a/assimp/xmake.lua#L102

**Comment by Kethers** [comment]
> 这个的版本限制得调整下，可以提个 pr 过来 https://github.com/xmake-io/xmake-repo/blob/fb077c505b04a8e2c534da6828ab31e13d4ebf54/packages/a/assimp/xmake.lua#L102

It doesn't work or maybe I do it wrong. I would close it here since this issue should be in xmake-repo.
