### ISSUE TITLE
xrepo导出的包如何在另外机器上安装或导入

### ISSUE THREAD

**Issue by x1244** [xmake-io/xrepo#6]
### 描述讨论详情
我使用了xrepo安装了一个包，比如是`zlib`，我将它导出
```
> xrepo export -o /path/to/pkg zlib
```
发现导出包的目录结构与原始位置的目录结构不一致。
原目录结构为：`z/zlib/1.2.11/a593fa3f71e64cf790ec96898b34de8a`，导出包的目录结构直接为`zlib_1.2.11_a593fa3f71e64cf790ec96898b34de8a`。
那么如果我要在另外一台机器上，能否将这个包导入或安装呢？

之所提这个问题，是因为需要在网络受限环境中使用依赖包。如果可以在开放的网络上下载安装需要的包，再将这个包导出，能导出的包复制或安装到受限环境中使用就好了。

还是说只能将依赖包源码下载到受限环境中，添加包仓库，像说明中指出的一样：
```
$ xrepo add-repo myrepo https://github.com/mygroup/myrepo
```
或者手动修改目录使之与xrepo管理目录适配呢？
或者能否在`add_requires`中设置包目录呢？

**Comment by waruqi** [comment]
以改进支持，见：https://github.com/xmake-io/xmake/issues/1338
