### ISSUE TITLE
xrepo search vcpkg::flashlight-cuda gives no results

### ISSUE THREAD

**Issue by oblitum** [xmake-io/xrepo#9]
> Note: If you use the fuzzy expressions such as 'can't use/no effect/problem/error', but don't give any relevant auxiliary information according to the template below, this issue will be not replied.

### Describe the bug

`xrepo search vcpkg::flashlight-cuda` doesn't return a result for the flashlight-cuda package on vcpkg.

### Expected behavior

It should return some result, as the package actually exists on vcpkg.

### Error output
If applicable, please add verbose the errors output to help us analyze your problem.

> If it is a xmake related compilation problem, please add the `-v -D` parameter and give the detailed compilation output information.

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.5.3+202104301933,
- os: ArchLinux
- target platform: Linux

**Comment by waruqi** [comment]
xrepo does not yet support searching for packages in third-party package management. Currently, only packages in xmake-repo can be searched.

**Comment by oblitum** [comment]
I'll leave it open as feature request.

**Comment by waruqi** [comment]
I have support it on xmake/dev. see https://github.com/xmake-io/xmake/issues/1422

**Comment by oblitum** [comment]
Nice, thanks. Waiting for a new release so I can give it a try.
